### ISSUE TITLE
Include custom CSS files

### ISSUE THREAD

**Issue by launsi** [slidesdown/slidesdown#14]
Hi, is there a way to easily add custom css files or extend the reveal.js themes when running the docker version of slidesdown?

I know that you can add css classes and styles to the markdown & html elements, but I would like to insert custom global themes so that I don't have customize each element separately.

**Comment by jceb** [comment]
Yes, this is possible. There are two ways:

1. You can create a custom theme (https://github.com/slidesdown/slidesdown/blob/main/examples/SLIDES.md?plain=1#L13) and add custom CSS to it. For example: https://github.com/identinet/slidesdown-theme.
2. You can use the `additional-stylesheet` property in the front-matter to reference an externally hosted style sheet. See https://github.com/slidesdown/slidesdown/blob/main/public/plugin/slidesdown.js#L771

Option 2 probably comes closest to your question.
