### ISSUE TITLE
Feature Request: Simple command runner to serve markdown slides

### ISSUE THREAD

**Issue by prashanth-hegde** [slidesdown/slidesdown#2]
I loved the idea of slidesdown and how simple it makes to render slides. 
It also has all the cool reveal.js plugins I care about. 

I am a javascript noob, but still interested in writing only Markdown to render my ideas. 
As it stands currently, it is a little cumbersome to render a standalone markdown file as slides.
So, if there is a simple dockerized way to render (an example shown below) slides by providing my md as input, that'd be awesome. 

For example: 
```shell
# this would render my markdown file as slide on port 8080 
docker run --rm -p 8080:8080 slidesdown:latest my_markdown_file.md
```

OR 

```shell
# this would convert a given markdown file into a standalone html file and prints output to console,
# which can then be redirected to a desired file
docker run --rm slidesdown:latest <my_markdown_file>

# redirect the output to a desired file 
docker run --rm slidesdown:latest my_markdown_file.md > my_html_file.html
```

I have been trying to tinker with the scripts and dependencies on my local machine, but I keep hitting into snags like these 
```shell
ERROR: failed to solve: failed to compute cache key: failed to calculate checksum of ref moby::tj3k8njk7xe2ms0plcmwgfcso: "/Justfile": not found
```

OR 

```shell
error: Recipe `update-chartjs` failed on line 50 with exit code 64
```

Also, having a dockerized version to quickly run presentations (or even have them output to a standalone html files) helps in 
* automating a bunch of workflows to convert markdown into *html files
* deploying docker container in a private environment to render markdown files as presentations

I'd love to help with PR and contributions, but I haven't successfully built the image yet. I will keep trying.

**Comment by jceb** [comment]
Hi, thanks for raising the issue. You can use the `slidesdown` tool do just what you requested. The installation instructions are found here: https://github.com/slidesdown/slidesdown#cli. Examples are listed just below: https://github.com/slidesdown/slidesdown#usage-1.
The tool also provides a PDF rendering feature. If you want to get HTML output, I suggest you let `slidsedown` render the slideshow in your browser. Next click "Save Page" and store it locally, including all dependencies. You could also use a tool like `monolith` that downloads the entire presentation. However, it isn't 100% compatible as it won't store background images of slides, hence I'm hesitant towards adding it as a feature.

Please reopen the issue if you have other questions. Would you open another issue for the HTML rendering feature?
